<a href="https://colab.research.google.com/github/grkenney/WinSPIRE-HLC-Python/blob/main/Notebooks/Day_2.1_Introduction_to_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Review

* variables
* data type
* list
* length
* indexing lists

# Introduction to Packages

# Introduction to Pandas

You may have used a program like Microsoft Excel or Google Sheets to record data or perform calculations for school. Datasets are often organized in rows and columns. Does anyone have an example of a using spreadsheets in school? (e.g. recording measurements in biology class, budgeting for personal finance in econ, etc.)



| Product | Price | Quantity Sold |
|--------------|-------------|------------------------|
| Apples  | \$ 1.50 | 26 |
| Bananas | \$  0.50 | 32 |
| Lemons | \$ 1.99 | 17 |

In this case, we have prices of fruit from a grocery store. Each row in this dataset is a type of fruit, and each column is an observation or measurement. What measurements do we have here?

**Measurements**:

To handle data in Python, we use a package called called `pandas`. (Despite the name, it actually doesn't have anything to do with panda bears).
Before we can use the package, we need to import it. Try writing a line of code to import the `pandas` package:

In [1]:
# write the code to import the package
import pandas ##

We're going to be using `pandas` a lot. To save us some time typing, let's tell Python to rename the package for us to something a little shorter:

In [2]:
import pandas as pd ##

Adding "`as pd`" to our import statement tells Python that every time we use `pd`, we actually mean `pandas`. It's like giving the package a nickname! Most people use this same nickname for `pandas`, so if you see other people's code, you'll know that `pd` means `pandas`.

Now that we've imported `pandas`, we're ready to use it. Datasets are stored in `pandas` in a special container called a `DataFrame`. `DataFrames` help us handle data that are organized in rows and columns, just like the grocery store dataset above. We can store that data in a `DataFrame` by calling the `DataFrame` function:

In [3]:
pd.DataFrame({'Product': ['Apples', 'Bananas', 'Lemons'],
              'Price': [1.50, 0.50, 1.99],
              'QuantitySold': [26, 32, 17]})

   Product  Price  QuantitySold
0   Apples   1.50            26
1  Bananas   0.50            32
2   Lemons   1.99            17

Run the above cell and see what happens! There are a few things to notice:

1. Python helpfully showed us what our `DataFrame` looks like with rows and columns.
1. Python gave each row in the `DataFrame` a number, starting from zero. Does that remind you of something about lists?

When we ran that cell, Python showed us what the `DataFrame` looks like, but it didn't save the `DataFrame` anywhere. If we want to do more things with it, we'll need to save it to a variable. In the below cell to save the `DataFrame` to a variable called `fruit_data`:

(Hint: you may want to copy & paste the cell above to get started!)

In [4]:
# save the DataFrame to a variable called fruit_data
fruit_data = pd.DataFrame({'Product': ['Apples', 'Bananas', 'Lemons'],
              'Price': [1.50, 0.50, 1.99],
              'QuantitySold': [26, 32, 17]})

When we run the above cell, does anything happen?

Since we saved the `DataFrame` to a variable, Python assumed that we don't want to take a peek at it. If we do want to see what our `DataFrame` looks like, we can write the variable on a line by itself like this:

In [5]:
fruit_data ##

   Product  Price  QuantitySold
0   Apples   1.50            26
1  Bananas   0.50            32
2   Lemons   1.99            17

Sometimes we don't want to see all of the data at once. To view just the first few rows of a `DataFrame`, we use a method called `head`.

Recall: methods are special functions that belong to certain types of variables. They only work with the type of variable that they belong to, so running `head` on a variable that isn't a `DataFrame` will not work.

Let's use the `head` method to view only the first two rows of our fruit data:

In [16]:
# print head of fruit_data
fruit_data.head(2) ##

   Product  Price  QuantitySold
0   Apples    1.5            26
1  Bananas    0.5            32

After typing `head`, the name of the method, we wrote the number `2` between the parentheses. This told `head` that we wanted to see only the first two lines of our `DataFrame`. What would you do if you only wanted to see the first line of `fruit_data`?

In [17]:
# write the code to see only the first line of the DataFrame
fruit_data.head(1) ##

  Product  Price  QuantitySold
0  Apples    1.5            26

Great! What if instead of viewing the first few lines, we wanted to see the last few lines? For that we will use another method called `tail`. It is very similar to `head`, except it will show us the last few lines instead of the first few. Try writing a line of code to view the very last line of `fruit_data`:

In [18]:
# get last line of fruit_data
fruit_data.tail(1) ##

  Product  Price  QuantitySold
2  Lemons   1.99            17

`head` and `tail` are especially useful for big datasets with many rows so you can get a sense for what the `DataFrame` looks like without flooding your notebook with too much information. They will come in handy later!

Now let's talk about the types of variables we have in the `fruit_data` `DataFrame`. What are some of the types of variables we've learned about in Python?

**Types:**

Based on what you know about these types of variables, what `type` do you think the values in each of the columns belong to in `fruit_data`?

**Type of the `Product` column:**

**Type of the `Price` column:**

**Type of the `QuantitySold` column:**

Notice how each of the columns in `fruit_data` have different types. That's one of the many cool things about `pandas` -- it let's us store many different types of data in `DataFrames`.

# Reading Data with Pandas

We've learned how `pandas` stores data as rows and columns in `DataFrames`. We previously used a small dataset that was hard-coded right in the notebook. But in the real world, we want to be able to use large datasets that can't be easily hard-coded or typed out by hand. One way that we can store large datasets as files is in the CSV format. This is a format which can be opened by many different programs like Excel, Google Sheets, or our Python programs, which allows us to share data easily.

Let's read our dataset into Python with `pandas`! We'll use a function called `read_csv`.  Our dataset is in our GitHub repository, and we need to tell `read_csv` exactly where to find it. `read_csv` will create a `DataFrame` for us:

In [21]:
# load the csv
url = 'https://github.com/grkenney/WinSPIRE-HLC-Python/raw/refs/heads/main/data/sample_data_expression_06092026.csv'
df = pd.read_csv(url)

Since we saved the data to a variable, `pandas` didn't show us what it looks like. How would you view the beginning of the `DataFrame` without seeing every row? Try it below:

In [23]:
# View just the beginning of the DataFrame
df.head()

   sample_id  well  timepoint     MKI67      MTOR       BAX       IRF1
0     657317     1          0  1.004377  1.379025  0.799135   0.672194
1     657317     2          8  0.894172  1.345400  0.956142   0.756379
2     657317     3         16  0.679445  1.098444  1.209928  99.000000
3     657317     4         24  0.721341  1.063588  1.586136   0.643022
4     407401     5          0  1.091682  0.843497  0.354864   0.489234

Look at the column names of the `DataFrame`.

Based on the column names and some of the values in the `DataFrame`, what do you think the rows each represent?

Now let's take a look at the end of the `DataFrame`:

In [24]:
# View the end of the DataFrame
df.tail()

     sample_id  well  timepoint     MKI67      MTOR       BAX      IRF1
115     199598    26         24  0.346927  0.144315  1.302101  1.838012
116     871144    27          0  0.881421  1.514194  0.660141  0.490321
117     871144    28          8  0.817965  1.407120  0.815591  0.537545
118     871144    29         16  0.708894  1.197898  0.972522  0.499416
119     871144    30         24  0.541472  1.092223  1.341830  0.534427

Notice the numbers on the far left side of the `DataFrame`. `pandas` assigned a number to every row. What number did `pandas` assign to the very first row of the `DataFrame`? (Scroll up if you need to.) So how many rows do we have in this `DataFrame`?

**Number of rows:** ?

The column of numbers that label the rows is called the `index` of the `DataFrame`. The `index` is an `attribute`, a special variable which belongs to variables of the `DataFrame` type. An example of an attribute would be if you had a variable `dog` with an attribute `dog.owner` to store the name of the person who owns the dog.

We can view the `DataFrame`'s `index` like this:

In [25]:
# view the index
df.index ##

RangeIndex(start=0, stop=120, step=1)

So our index starts at 0, ends at ?, and increases by 1 for each row.
Another way to count the number of rows is to take the length of the index using the `len` function:

In [26]:
# get the length of the index
len(df.index) ##

120

Like the `index` labels the rows of the `DataFrame`, there is an `attribute` called `columns` that refers to the columns of the `DataFrame`. Let's take a look:

In [29]:
# view the columns
df.columns ##

Index(['sample_id', 'well', 'timepoint', 'MKI67', 'MTOR', 'BAX', 'IRF1'], dtype='object')

We could count the number of columns -- there aren't too many -- but what's the fun in that? Let's write a line of code to tell us the number of columns:

In [30]:
# length of the DataFrame's columns
len(df.columns) ##

7

Conveniently, we can also call `len` on the `DataFrame` itself. Try it here! Is the result equal to the number of rows or the number of columns?

In [31]:
# use len on df
len(df) ##

120

**Exercise:** Based on the number of rows and columns, how many data points are in the `DataFrame`?

In [36]:
# calculate the number of data points
7 * 120 ##

840

Instead of typing the number of rows and columns in the DataFrame, we could put both commands with `len` on the same line. Try it here:

In [38]:
# Multiply the length of rows & columns without typing numbers
len(df.columns) * len(df) ##

840

**Exercise:** Now, try using the `size` attribute to get the same information.

In [39]:
df.size ##

840

This way, if the data changes, we can quickly re-run the above cell to find the number of values in it, without having to manually type out the number of rows and columns.

That's a lot more data than we've handled before. But that's nothing for `pandas` -- it can handle `DataFrames` with *millions* of rows! Data scientists use `pandas` to handle very large datasets from the real world.

You just learned:

- How to read datasets into `pandas` `DataFrames`.
- The `index` and `columns` attributes of `DataFrames`.
- How to find the number of rows, columns, and number of data points in a `DataFrame`.